# Every field here must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_id=nofogmod
mod_version=1.0
mod_name=The NoFog Mod
description=A simple mod that removes fog.
mod_author=Dillon8775
credits=Dillon8775, MannyQUESO
license=All rights reserved unless explicitly stated.
logo=assets/nofogmod/icon
mc_version=mc26.3
supported_mc_versions=26.3
# Use "-alpha.# for snapshots, "-pre.# for pre-releases
minecraft_version_range=>=26.3-pre.3 <26.4
group=net.dillon.nofogmod

# Links
homepage=https://modrinth.com/mod/the-nofog-mod
sources=https://github.com/Dillon8775/The-NoFog-Mod
issues=https://github.com/Dillon8775/The-NoFog-Mod/issues
discord=https://discord.gg/vfqEAn4YFy

# Common
java_version=25
minecraft_version=26.3-pre-3
devauth_enabled=1

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-pre-3-1

# Dependencies
## Balm
### https://maven.twelveiterations.com/service/rest/repository/browse/maven-public/net/blay09/mods/balm-common/
balm_version=26.3.0.1-SNAPSHOT
## Mod Menu
### https://modrinth.com/mod/modmenu/versions
modmenu_version=21.0.0-alpha.1

# Fabric
## https://fabricmc.net/develop/
fabric_version=0.160.1+26.3
fabric_loader_version=0.19.5

# NeoForge
## https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.0-beta
neoforge_loader_version_range=[4,)

# Other (not required in multiloader-common.gradle)
curseforge_project_id=1446602
modrinth_project_id=wAEWD77L
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false